### ISSUE TITLE
S3: Dialogue window when loading EEPROM

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#364] opened 2016-07-13 21:17 UTC
![object](https://cloud.githubusercontent.com/assets/20099916/16819824/0a1d1490-4903-11e6-860c-ff4a1aac9009.PNG)

I got this dialogue popup in Google Chrome when I tried loading EEPROM on the S3, it happened 5-6 times before it went away. It has shown up again once or twice since. Also, no Spin code was sent or compiled when this happened.

**Comment by DarkmatterVale** [comment] 2016-07-14 22:53
@dcarrier-parallax Isn't this in your domain?

**Comment by dcarrier-parallax** [comment] 2016-07-16 02:21
I don't have any experience using Blockly to load code; I've only been working on making blocks.

If the issue still persists, Michel may be best qualified to look into it.

**Comment by DarkmatterVale** [comment] 2016-07-17 23:10
This should be a pretty simple thing to fix. It appears you have an alert() call within the javascript somewhere...

**Comment by kgracey** [comment] 2016-08-24 17:50
Has anybody else seen this issue occur again? Can somebody verify this is still an issue?

**Comment by zfi** [comment] 2016-08-25 17:43
@CarsonGracey can you attempt to load the EEPROM on the S3 again with the current code base?

**Comment by PropGit** [comment] 2016-09-01 21:00
Closing because this issue has not been seen by others; it has non-duplicate-able.

**Comment by dcarrier-parallax** [comment] 2016-10-06 18:30
I managed to reproduce this issue.  I suspended and then resumed my computer and after resuming, the com port drop-down list was blank.  When selecting to load RAM or EEPROM with a blank com port, the web interface would create an alert box displaying the text "[object Object]".

It appears to be that an error handler is creating the message when trying to open an invalid com port.

**Comment by dcarrier-parallax** [comment] 2016-10-06 18:50
After restarting The BlocklyProp web interface, the server, and BlocklyPropClient, the com port drop-down list is still blank, but the error message is a slightly more sensible:

> error: opening serial port ''
> Error is : No such file or directory

It appears now that the "[object Object]" alert isn't from a lack of a selected com port, but from a lack of communications between some combination of the local BlocklyProp web interface, the BlocklyPropClient, and the BlocklyProp web server.

I have verified this by running a working BlocklyProp session, then disconnecting from the internet and trying to load RAM or EEPROM.  This reproducibly creates the "[object Object]" alert.

If the web interface does not receive the expected communications, the alert or error message should make that clear.

**Comment by MatzElectronics** [comment] 2016-12-12 02:18
@zfi @dcarrier-parallax Is this exclusive to SPIN?  If so - let's close it since we are transitioning to C.

**Comment by zfi** [comment] 2016-12-12 02:42
This issue is language agnostic. It appears that the BlocklyProp Client is losing connection to the serial port but is not or is unable to notify the browser of the condition. This issue needs to be resolved between the client and the BlocklyProp server.

**Comment by MatzElectronics** [comment] 2017-07-17 07:30
Duplicate with #955

**Closed by MatzElectronics** 2017-07-17 07:30 UTC
Labels: bug
