### ISSUE TITLE
S3 block: LED states not working properly

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#362] opened 2016-07-13 20:02 UTC
Three pieces of information for you @dcarrier-parallax, starting with my blocks:
![screen shot 2016-07-13 at 1 13 13 pm](https://cloud.githubusercontent.com/assets/9534148/16817875/bdb6773a-48f9-11e6-904a-4ba7cf552b7b.png)
and the code it produces:
```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Start


PUB Start

  Scribbler.SetLED(Scribbler#CENTER, Scribbler#RED)
  Scribbler.SetLED(Scribbler#LEFT, Scribbler#AMBER)
  Scribbler.SetLED(Scribbler#RIGHT, Scribbler#GREEN)
```
and the result is that the right LED flashes green (it should be solid, and the left and center should be red and amber, respectively. I'm not sure about the code underneath the top Spin file you've created. It's possible the S3 schematic requires these to be managed differently than you have coded. I'm not sure - let me know what I can do to help this one out.

**Comment by dcarrier-parallax** [comment] 2016-07-14 21:17
Duplicate of: https://github.com/parallaxinc/BlocklyProp/issues/374, caused by crash of Block_Wrapper.spin

**Closed** 2016-07-14 21:18 UTC
