### ISSUE TITLE
Variable type (masked boolean) that has HIGH LOW values and can be switched using NOT (or custom NOT)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#182] opened 2016-05-04 13:51 UTC
For programmatically switching things between HIGH and LOW, we should have a variable type that does this.  

Certainly, this is "behind the scenes" just a boolean, but for the user it'd be nice to be able to set vars to the states HIGH or LOW and say var = NOT (var)  to switch.  

Ideally, ideally - it would also be possible to PRINT this variable (and get "HIGH" or "LOW") [ or "HI" and "LO" if you wanted to make it conserve space and have fixed-width.

**Comment by DarkmatterVale** [comment] 2016-05-04 20:14
Hi Dr. Brady,

I'm a little confused as to what you mean here. I can currently use "NOT" with a boolean without an issue:

![screen shot 2016-05-04 at 4 11 22 pm](https://cloud.githubusercontent.com/assets/6094957/15027649/dd6455c0-1212-11e6-811c-4e56c942f127.png)

Regarding the ability to print this variable, I'm not sure how we can accomplish that. If we are assuming you would like to be able to print out a true/false as "HIGH"/"LOW" using the normal print block, I believe that something would have to be added to the print block for this special case. The issue arises, however,  that you would be changing all "1"s within the text to "HIGH"s and all "0"s to "LOW"s.

**Comment by cbradyatinquire** [comment] 2016-05-04 22:16
right -> so my thinking here is based on kids that are thinking about HIGH/LOW differently from TRUE/FALSE and 1/0.

if we create an essentially “fake" variable type which takes on the two values HIGH and LOW, then that type’s literal values can appear.  One reason, actually, to have this type is that it could have its own ways to handle toString()  and printing.  

if we do NOT create this fake variable type, then to programmatically control, say, LED on/off state, we would want to have the ability to enter a boolean into the second argument of the Set LED [number] [on-off state]  block. 

if we did THAT, we would want to have all of the blocks that deal with HIGH/LOW hide that language, and use true/false instead.

(in my opinion)

:)
-C

**Comment by DarkmatterVale** [comment] 2016-06-23 21:23
I have created a "fake" variable in my new PR for HIGH/LOW declarations, which is pretty much a duplicate of the Boolean block but with different UI text. I believe this is what we want (minus the printing...we can create a separate issue for that if you would like).

**Closed** 2016-06-28 00:30 UTC
Labels: PR
