### ISSUE TITLE
Terminal Capabilities

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#321] opened 2016-07-08 18:12 UTC
@michel-cf - What are the BlocklyProp Terminal capabilities in terms of display manipulation and cursor movement?  Is it currently only able to display input as scrolling text (left-to-right, top-to-bottom) and supporting only the CR (or LF?) control character?  

We have a need for at least a little more manipulation capability based on control characters in the input serial stream.  Such examples are Home, Tab, Cursor left/right/up/down, position cursor, and clear to end of line.

As an example, here's a description of what is supported in the Parallax-IDE Debug Terminal.  Keep in mind that I don't yet know if we'd want to support all of these, but they are here for explanation and potential discussion.
#### Visible Characters
- ASCII 32-127 and 160-255 (all visible characters) are displayed as they are received from the microcontroller
#### Control Characters
- ASCII 17-31 and 128-159 are displayed only as spaces, unless they are part of a multi-character control sequence (see below) 
- ASCII 0 or 16 (**Clear Screen**) clears the entire Receive pane and scrolls the display back up to the topmost position
- ASCII 1 (**Home Cursor**) moves the cursor to the first character of the first line in the Receive pane (location 0,0) but does not scroll the display up if that position is not visible.
- ASCII 2 (**Position Cursor (x,y)**) is the start of a special, three-character control sequence; the next two characters received are considered a part of it.  This control character sequence moves the cursor to the x column of the y row of the Receive pane.  The two characters received after the ASCII 2 represent the absolute x position (0-255) and absolute y position (0-255).  For reference, the Home Cursor control character moves the cursor to position 0,0.  Note that this control character sequence does not autoscroll the display.
  - A flagged state is recommended for processing this multi-character sequence
- ASCII 3 (**Move Cursor Left**) moves the cursor one character to the left to a minimum position of column 0 (it does not wrap back around to the end the line).  Note that this control character does not autoscroll the display.
- ASCII 4 (**Move Cursor Right**) moves the cursor one character to the right to a maximum position of column 255 (it does not wrap back around to the beginning of the line).  Note that this control character does not autoscroll the display.
- ASCII 5 (**Move Cursor Up**) moves the cursor one line up, to a minimum row of 0 (it does not wrap back to the end of the display buffer).  Note that this control character does not autoscroll the display.
- ASCII 6 (**Move Cursor Down**) moves the cursor one line down, creating new lines as necessary (it does not wrap back to the top of the display buffer).  Note that this control character does not autoscroll the display.
- ASCII 7 (**Beep Speaker**) causes the application to play the system’s bell tone.
- ASCII 8 (**Backspace**) performs a backspace operation- moves cursor back (left) one character, deleting the preceding character in the process.  Exception: If the cursor was on column 0 of a line, the operation simply moves it just to the right of the last character of the previous line (if a previous line exists); the newline character between the lines is not deleted and concatenation of one line with a previous line is not performed.  Note that this control character does not autoscroll the display.
- ASCII 9 (**Tab**) performs a horizontal tab operation; moving the cursor right to the next position beyond its current column that is a multiple of 8 from absolute 0 (8,16,24, etc.).  Note that this control character does not autoscroll the display.
- ASCII 10 (**Line Feed**) or 13 (**New Line**) (individually only; not contiguous pair) or ASCII 10,13 or 13,10 (as contiguous pairs) act as a single newline, causing the display to move the cursor to the start of the next line.  Each _individual_ and each _contiguous pair_ acts as a single newline such that multiple _individuals_ and _multiple _contiguous pairs_ act as multiple newlines.
  - Since no two bytes are guaranteed to be visible in the receive buffer each time it is parsed, it’s best to treat the first character as an individual (emitting a newline on the display) and if it’s pairing character happens to appear next (regardless of cadence of arrival) simply ignore it, moving on to the next character instead.
  - Note that no existing text is ever split or moved by this operation; if the cursor is in the middle of any existing line or text, the newline operation simply moves the cursor to the start of the next line without affecting any existing text on either side of it previous position.
  - Note that this control character sequence autoscrolls the display only if the display was already displaying the last line.
- ASCII 11 (**Clear to End of Line**) clears all characters on the line starting at the cursor position and extending all the way to the end of the line, regardless of what is visible in the current display.  Note that this control character does not autoscroll the display.
- ASCII 12 (**Clear Lines Below**) clears all characters starting with the line the cursor is on and extending all the way to the end of the display’s buffer, regardless of what is visible in the current display.  Note that this control character does not autoscroll the display.
- ASCII 14 (**Position Cursor (x)**) is the start of a special, two-character control sequence; the next character received is considered a part of it.  This control character sequence moves the cursor to the x column of the current cursor line of the Receive pane.  The character received after the ASCII 14 represents the absolute x position (0-255).  Note that this control character sequence does not autoscroll the display.
  - A flagged state is recommended for processing this multi-character sequence
- ASCII 15 (**Position Cursor (y)**) is the start of a special, two-character control sequence; the next character received is considered a part of it.  This control character sequence moves the cursor to the y row of Receive pane, maintaining the same column position.  The character received after the ASCII 15 represents the absolute y position (0-255).  Note that this control character sequence does not autoscroll the display.
  - A flagged state is recommended for processing this multi-character sequence

**Comment by kgracey** [comment] 2016-07-08 20:10
I’d like us to support a very small number of these options so we can have a few more formatting controls during release. If it helps, Michel, we can make a super short list. The number of blocks to support this entire list would be pretty big.

**Comment by kgracey** [comment] 2016-07-13 20:23
I'd like to free up this from the current deadlock by asking @michel-cf to take a look and respond. 

I've given the terminal needs some thought and believe they can be very simple. After working with some sensors, multiple inputs, and robots, these are the minimal formatters that would be nice to have:

- Home Cursor
- Position Cursor (X,Y)
- Clear Screen
- New Line

Along with a larger font size this would give us enough control to be useful with the Print screen.  @PropGit could you take a quick look at what I'm asking for?

**Comment by michel-cf** [comment] 2016-07-13 20:52
I just finished a feature that will be put online today/in a few days.
I'll look further into this on Friday and over the weekend.

**Comment by PropGit** [comment] 2016-07-13 20:53
@michel-cf - Here's some more information that is important for this feature.  This is some information I described for the Parallax IDE's Debug Terminal, but applies here.

For these control characters to work as expected:
* Visible characters appear left-to-right, top-to-bottom as they arrive; scrolling the display as needed to show and emit a new line beyond the bottom of the display
* All characters emitted to the display do so in an overwrite fashion; no existing text is moved by any operation
* The “cursor” logically resides in a specific position (often after the last visible character emitted) but is not ever visible in the receive pane; however, it’s position marks the place the next visible character will naturally be placed
* Each line of the display should be designed to be a maximum of 256 characters wide; column 0 to 255
  * If text exceeds position 255, further text appears on the next line
  * The display does not wrap incoming text to the edge of the window, but rather wraps only to the logical end of the line
    * A horizontal scroll bar may appear to indicate more text to the right or left edges of the window

**Comment by michel-cf** [comment] 2016-07-16 21:34
I've gotten this far:
![image](https://cloud.githubusercontent.com/assets/5745991/16897308/983442d8-4bad-11e6-8336-1cb92db8b3c2.png)
![image](https://cloud.githubusercontent.com/assets/5745991/16897311/a6360aba-4bad-11e6-8d90-11761088ef9b.png)
```
'SERIAL_TERMINAL USED
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR
  long row

OBJ
  serial    : "Parallax Serial Terminal"

PUB Setup
  serial.Start( 115200 )
  Start


PUB Start

  serial.Str(String("Test"))
  serial.Char(serial#NL)
  serial.Char(serial#LF)
  serial.Str(String("Test line 2"))
  waitcnt(clkfreq / 1000 * 1000 + cnt)
  serial.Clear
  row := 1
  repeat 24
    serial.PositionX(13)
    serial.PositionY(row)
    serial.Dec(row)
    row := row + 1
    waitcnt(clkfreq / 1000 * 1000 + cnt)

  serial.Str(String("Hallo"))
```

**Comment by PropGit** [comment] 2016-07-21 23:11
@michel-cf  - That's starting to look great.  
I noticed the __Serial lear__ block - is that the same as would be __Serial transmit control character "cls"__?

Be careful to make the block consistent with capitalization, following the other blocks' examples.

@kgracey - I'm wondering if it'd be better to just have a __serial "control"__ block whose control list includes _clear_, _carriage return_, _new line_, etc., and also another that's __serial position "x,y" #, #__ where the x,y list can be "x", "y", or "x,y" and the column and row value can be included in the next fields.

**Comment by michel-cf** [comment] 2016-07-22 11:01
There was no control character in the list:
![image](https://cloud.githubusercontent.com/assets/5745991/17055292/2427aff2-500c-11e6-87aa-816ca373442b.png)

And while going through the Parallax Serial Terminal object, I noticed the clear method. So I called that one.

**Comment by kgracey** [comment] 2016-07-29 17:22
@CarsonGracey you can create blocks for closing this one up. The specific list is here https://github.com/parallaxinc/BlocklyProp/issues/321#issuecomment-232475351 (above). You can do these with a pull-down menu if you desire.

**Comment by PropGit** [comment] 2016-07-29 21:24
@CarsonGracey - For this issue to be addressed for our needs as of now, I've created the subset checklist below based on what Ken asked for, what I think he's implemented, and what may have naturally been included already.

When testing, please...

1. post a message(s) indicating __tested and verified as implemented / some implemented / mostly implemented__,  and,
2. check off the items in this post (below) that you've verified fully implemented.

## Terminal Features for Public Release # 1
### General Behavior
For the terminal to work as expected:
- [ ] Visible characters appear left-to-right, top-to-bottom as they arrive; scrolling the display as needed to show and emit a new line beyond the bottom of the display
- [ ] All characters emitted to the display do so in an overwrite fashion; no existing text is moved relative to each other by any operation
- [ ] The “cursor” logically resides in a specific position (often after the last visible character emitted) but is not ever visible in the receive pane; however, it’s position marks the place the next visible character will naturally be placed
- [ ] Each line of the display should be designed to be a maximum of 256 characters wide; column 0 to 255
  - [ ] If text exceeds position 255, further text appears on the next line
  - [ ] The display does not wrap incoming text to the edge of the window, but rather wraps only to the logical end of the line
    - [ ] A horizontal scroll bar may appear to indicate more text to the right or left edges of the window

### Visible Characters
- [ ] ASCII 32-127 are displayed as they are received from the microcontroller
- [ ] ASCII 160-255 are displayed as they are received from the microcontroller _(this one is optional for now)_

### Control Characters
- [ ] ASCII 0 or 16 (__Clear Screen__) clears the entire Receive pane and scrolls the display back up to the topmost position
- [ ] ASCII 1 (__Home Cursor__) moves the cursor to the first character of the first line in the Receive pane (location 0,0) but does not scroll the display up if that position is not visible.
- [ ] ASCII 2 (__Position Cursor (x,y)__) is the start of a special, three-character control sequence; the next two characters received are considered a part of it.  This control character sequence moves the cursor to the x column of the y row of the Receive pane.  The two characters received after the ASCII 2 represent the absolute x position (0-255) and absolute y position (0-255).  For reference, the Home Cursor control character moves the cursor to position 0,0.  Note that this control character sequence does not autoscroll the display.
- [ ] 13 (__New Line__) creates a new line, causing the display to move the cursor to the start of the next line.
  * Note that this control character sequence autoscrolls the display only if the display was already displaying the last line.
  * Note that no existing text is ever split or moved by this operation; if the cursor is in the middle of any existing line or text, the newline operation simply moves the cursor to the start of the next line without affecting any existing text on either side of it previous position.
- [ ] ASCII 14 (__Position Cursor (x)__) is the start of a special, two-character control sequence; the next character received is considered a part of it.  This control character sequence moves the cursor to the x column of the current cursor line of the Receive pane.  The character received after the ASCII 14 represents the absolute x position (0-255).  Note that this control character sequence does not autoscroll the display.
- [ ] ASCII 15 (__Position Cursor (y)__) is the start of a special, two-character control sequence; the next character received is considered a part of it.  This control character sequence moves the cursor to the y row of Receive pane, maintaining the same column position.  The character received after the ASCII 15 represents the absolute y position (0-255).  Note that this control character sequence does not autoscroll the display.

**Comment by michel-cf** [comment] 2016-08-07 16:50
- ASCII 2 Position cursor x,y is now also done (on top of individual positioning)
- New line now includes a carriage return

**Comment by kgracey** [comment] 2016-08-09 20:43
@PropGit Jeff could you specifically take a look at the Print blocks for both C and Spin and see that they are properly presented? Now that we seem to have some terminal support we need to make sure our blocks take advantage of these features. And we need this done quickly, unfortunately, so we can get the S3 docs done (this weekend).

**Comment by PropGit** [comment] 2016-08-09 23:17
@kgracey - yes.  No changes or verification has been done on this yet, correct?

**Comment by zfi** [comment] 2016-08-24 06:25
@PropGit Are you able to complete the tests for this issue or do you want to hand it off for reassignment?

**Comment by PropGit** [comment] 2016-08-24 16:46
@zfi - I'm completing what tests I can right now.  There are problems with the current implementation preventing me from actually performing all tests successfully, so I'm making separate issues to address them and would like to leave this issue open as an overall tracker of implemented and tested progress.

**Comment by PropGit** [comment] 2016-08-24 17:12
The [post above](https://github.com/parallaxinc/BlocklyProp/issues/321#issuecomment-236297473) tracks what features have been implemented and verified correct (checkmarks indicate verified).  As of now, all General Behavior is correct, the important Visible Characters are correct, and Clear Screen, New Line, Position Cursor (x) and Position Cursor (y) have partially correct functionality.

Issues have been created for noted problems.

**Comment by PropGit** [comment] 2016-08-26 00:34
I'm moving this issue to the __November 2016__ milestone because, as a whole, I expect it to be fully completed by then, and as of now, the most important sub-issues have been derived from it and are being addressed within the context of the current __Public Release # 1__ milestone.

**Comment by MatzElectronics** [comment] 2016-08-29 22:14
These blocks:
![image](https://cloud.githubusercontent.com/assets/19737272/18069028/49882a1e-6df9-11e6-8b65-d1f8ad2bfe03.png)

Generated this output:
![image](https://cloud.githubusercontent.com/assets/19737272/18069012/32939410-6df9-11e6-9e60-8a305222bd34.png)

The problem is that it's not exactly row 2 and 10 - instead it's relative to the info at the top of the screen.  If I cleared the screen first, I'm sure it would have worked well.

Is is possible to move that connection information out of the terminal area into its own box?:
![image](https://cloud.githubusercontent.com/assets/19737272/18069238/896f0282-6dfa-11e6-831b-97d639051770.png)

**Comment by PropGit** [comment] 2016-08-30 02:20
@MatzElectronics - That post belongs in Issue #628.

**Comment by PropGit** [comment] 2016-11-16 04:08
#### For potential future use

If the terminal can not be made to solve the remaining problems noted, perhaps another open-source terminal would be better.  

See this Chrome Application:  https://chrome.google.com/webstore/detail/beagle-term/gkdofhllgfohlddimiiildbgoggdpoea?hl=en
and the chromium-hterm project: http://goo.gl/6e9UE

**Comment by michel-cf** [comment] 2016-11-16 08:37
Why would you presume that the terminal can't be improved to work according to Parallax logic?
I can't see any evidence in the comments that anyone has tried.

**Comment by zfi** [comment] 2016-11-16 17:07
@PropGit: Are the unchecked boxes in the Terminal Features block listed earlier in this thread the only outstanding issues? It seems that this is really close to being complete. Let's identify what is left to do and finish it.

**Comment by PropGit** [comment] 2016-11-28 20:24
@michel-cf - I think it can be made to do it all, but some of our issue requests were met with responses indicating it was not going well and difficult.

**Comment by PropGit** [comment] 2016-11-28 20:40
@zfi - Not the only outstanding issues with the Terminal, no, but yes they are the issues preventing me from closing _this_ issue.  Each of the unchecked items are already called out by other issues that I've entered at various times and are already a part of the [December milestone](https://github.com/parallaxinc/BlocklyProp/milestone/4).  They are also on the priority list I gave to @michel-cf .  As I see progress and verify during testing, I will check them off this list in this thread and will close it when done.

I do see one that isn't specifically described, so I'll create an issue for it now.  The rest are specifically described, or are a part of an overlapping issue already open.

**Comment by MatzElectronics** [comment] 2017-03-27 20:23
Update (More information to come soon): we are going to begin removing cursor positioning from documentation and push to deprecate the terminal cursor position block.  This should simplify the terminal itself, possibly allowing us to more easily resolve the other issues described in this thread.

**Comment by MatzElectronics** [comment] 2017-06-29 21:26
Latest update - setting this as the primary issue related to the terminal, and closing all other terminal issues.  I have draft code to replace the entire terminal, so many of the aforementioned issues will be address and/or not applicable to the new terminal code.
For anyone who wants to look, here is the draft code: http://jsfiddle.net/LZs2D/159/

**Comment by MatzElectronics** [comment] 2017-07-10 21:32
The terminal has been changed in Demo - this means that it needs to be tested against the checklist above.  Please report errors so I can work on getting them fixed.

**Comment by MatzElectronics** [comment] 2017-07-16 21:17
Tested against the list above.  Almost every item is working.  Some issues still present - it is possible to overload the terminal by sending A LOT of data all at once.  Not much that can be done about that...it's somewhat a function of JS, websockets, the need to b64 encode everything, etc.

Other issues (extended ASCII, ASCII 0-31) stem from the BPC not base64 encoding it's stream - causing the websocket to choke on illegal chars.  Again, outside of the scope of this issue - more an issue for the BPC repo.  Code now exists that expects the BPC version >= 0.7.0 to send a base64 encoded stream.

**Closed by MatzElectronics** 2017-07-16 21:17 UTC
Labels: In Demo, Requires Verification
