### ISSUE TITLE
Upload Block's Replace/Append buttons stuck in enabled state

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1667] opened 2019-05-09 18:52 UTC
[ While testing issue #1662 ]

After __Replace__'ng or __Append__'ng an svg to an existing project, further selection of the Upload Block File feature shows the __Replace__ and __Append__ buttons are still in the enabled state even though there is no file selected.

![image](https://user-images.githubusercontent.com/1266318/57478844-d354a200-7250-11e9-82ba-6277a4ac0423.png)

This was tested on Demo.

**Comment by MatzElectronics** [comment] 2019-05-20 18:25
This is caused by the same issue as #1664.  Moving the text above to that one and closing this one.

**Closed by MatzElectronics** 2019-05-20 18:25 UTC
Labels: bug
