### ISSUE TITLE
BlocklyProp Editor stops displaying a portion of the editor view

### ISSUE THREAD

**Issue by dgately** [parallaxinc/BlocklyProp#1331] opened 2018-01-05 20:44 UTC
When editing BlocklyProp code, moving blocks around sometimes results in the bottom portion of the editor view to be not displayed. Some blocks are only partially visible, being cut-off at some point about half-way down the editor view. See the attached .mov file (probably a Mac OS-only viewable video :-) ) 
[BlocklyPropEdit Bug 1.zip](https://github.com/parallaxinc/BlocklyProp/files/1607859/BlocklyPropEdit.Bug.1.zip)

**Comment by dgately** [comment] 2018-01-05 20:48
This is happening on a MacBook Pro, running Safari on OS version: macOS High Sierra 10.13.2

**Comment by PropGit** [comment] 2018-01-05 20:49
Thanks @dgately.  Is there anything that caused it to restore to normal?

@MatzElectronics @zfi - have any of you seen this on your Mac?

That horizontal line... does it represent a panel that's normally at the bottom of the screen?

**Comment by PropGit** [comment] 2018-01-05 20:50
The video is viewable on non-Mac with a compatible reader/codec.

**Comment by PropGit** [comment] 2018-01-05 20:50
Accidentally closed.  Restored now.

**Comment by MatzElectronics** [comment] 2018-01-05 23:41
This seems to only be a problem in Safari, and it is the height attribute SVG that is the block workspace inside of the DIV block that contains the block workspace.  Interestingly, if you reload the page after you've opened the project, this seems to stop happening.

I'll dig when I can, but it doesn't seem to affect Chrome or Firefox.

**Comment by PropGit** [comment] 2018-03-15 17:07
@MatzElectronics - Were you able to find any more about fixing this?  

Someone else just reported the same issue:

> Blockly does not work correctly on my MacBook Air running High Sierra.  4GB RAM

> Screen “splits” and you cannot access anything below the line unless you reduce the screen size to mouse print.  Exit and come back and it will be fine for a few minutes then repeats.  In the first screenshot, the code blocks have all disappeared because they are below the gray line.

![image](https://user-images.githubusercontent.com/1266318/37478913-909c9566-2838-11e8-8710-6108a8c8f1dc.png)

![image](https://user-images.githubusercontent.com/1266318/37478944-a392e04e-2838-11e8-94db-c10fd74f3fcc.png)

For now, I'll let him know that it doesn't seem to happen in Chrome or Firefox.

**Comment by MatzElectronics** [comment] 2018-03-15 17:20
Hi!  I did figure out what code changes cased this issue, but unfortunately
I'm not any closer to solving it.  It is a CSS/style problem on that
element where Safari appears to be unable to calculate the height of the
HTML element that contains the workspace.  This was caused when we stopped
using <frame> tags for the header, toolbox, and workspace, and instead
generate each of them as a <div>.

Because this issue is specific to Safari, and it does not appear in Chrome
or Firefox, it is also a low priority behind several other issues.

Although I may not be able to get to it in the near future, I would love
for the community to jump in and see if they can find a possible fix.  If
you start with the blocklyc.jsp file and it's included CSS, I'm sure a
solution can be found.

If you'd like an offline/HTML-JS only version to play around with to try
and diagnose/fix this, I'm happy to send one to you.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by zfi** [comment] 2018-03-15 18:20
@MatzElectronics  I have seen this before when tracking down warnings from the the template code in a number of .jsp files. If I correct the warning, the reported behavior begins. The issue may ultimately be the CSS, but the CSS might be getting hammered from the template language in the .jsp.

**Comment by PropGit** [comment] 2018-03-15 18:48
@zfi - are you saying the a correction to prevent the warning is actually causing this undesired UI behavior (as a side-effect, not the true source of the problem)?

**Comment by zfi** [comment] 2018-03-15 22:54
I'll reproduce the issue and document it here. It's related to an unresolved tag in the .jsp page. The IDE is unable to resolve it but it does appear to become resolvable at run-time. When I correct the warning in the IDE, the vertical space on the editor canvas becomes constricted to something like 300 pixels.

**Comment by MatzElectronics** [comment] 2018-03-15 23:13
Okay - this gave me the idea to run the generated html page through an HTML
validator - and there are A LOT of issues...so I'll work on correcting
them...maybe that will help.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by PropGit** [comment] 2018-03-16 15:05
Great find!  Thanks.

**Comment by MatzElectronics** [comment] 2018-03-20 08:36
@dgately please re-test, let me know if it now works.

**Comment by zfi** [comment] 2018-03-20 17:19
This should be tested on the Demo server, since that is where to code changes are happening. I was thinking that @dgately was using the production site when the issue was encountered.

**Comment by MatzElectronics** [comment] 2018-05-23 16:26
Appears to be working fine now.  Closing.

**Closed by MatzElectronics** 2018-05-23 16:26 UTC
Labels: In Demo, Requires Verification, bug
