### ISSUE TITLE
New projects not showing up in the "my projects" list

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1500] opened 2018-07-12 00:09 UTC
I have now created a couple of projects in demo, none are showing in the "My projects" list.  I can still access them via their project id in the URL so they are saving properly.

**Comment by zfi** [comment] 2018-07-12 02:08
@MatzElectronics, I am unable to reproduce this error on the demo server. What are the project id's for the projects that are not appearing in your Project List?

**Comment by zfi** [comment] 2019-02-06 22:33
Additional reports of projects 'disappearing' at random intervals and never return. Initial investigation has identified a missing project owner id on a few recent projects.

**Comment by zfi** [comment] 2019-02-07 19:15
Discovered a corner use case where a private, shared project cannot be duplicated by another user if the user is accessing the project through the encrypted shared link.

**Comment by zfi** [comment] 2019-02-08 05:00
This issue was probably related to the several use cases we found where the project owner's account was not always getting attached to a new project. 

Closing the issue. Please feel free to reopen it if the issue returns.

**Closed by zfi** 2019-02-08 05:00 UTC
