### ISSUE TITLE
Shared project link opens empty canvas for logged in users 

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#1114] opened 2017-07-28 17:52 UTC
Using the shared link to view a project bring the user to the Blockly canvas, but no blocks are rendered - only if the user is logged in. The link works as expected if the user is logged out when accessing the link.

Sample link:

http://blockly.parallax.com/blockly/projectlink?id=9290&key=f7622671-7e13-40b9-ad28-f70bb6175856

**Comment by MatzElectronics** [comment] 2017-07-29 03:16
I wonder if/how this might be related to #1103

**Comment by MatzElectronics** [comment] 2017-07-29 04:17
This is failing due to a race condition - using the shared link isn't spooling up everything in the right order, so that will need to be examined...

**Comment by zfi** [comment] 2017-07-29 04:29
Is this an issue within the Javascript codebase? If its on the Java side, I'd be glad to tackle it.

**Comment by MatzElectronics** [comment] 2017-07-29 04:32
I think it is in the browser-side JS, but I'm really going to have to work my way through it.  I think it will make the overall code more stable in the end, so the effort is definitely worth undertaking.

**Comment by MatzElectronics** [comment] 2017-08-10 21:57
@zfi @PropGit @kgracey Here's an idea - let's just dump the shared link thingy.  There are two other ways to share a project - email a blocks file or set your project to shared.  This shared link thing is nothing but a pain in the @$$.

**Comment by zfi** [comment] 2017-08-10 22:12
@MatzElectronics, let's get some fresh eyes on the issue - and - revisit the use case(s) for this feature. Can you briefly describe the race condition that is happening in the JS?

@paragitadmin, do you have any recollection of how this feature came to be in the first place?

**Comment by MatzElectronics** [comment] 2017-08-10 22:16
Sure - I wish I could, I'm only guessing that's the cause, because that
symptom is almost always caused when something tries to access an object or
element that has not finished loading.  I'm only beginning to wrap my head
around the back-and-forth that is happening between elements, frames, and
scripts, and it's quite a dance...

What I do know is that once we isolate problematic code, we've been able to
solve it by wrapping it in an onReady-style event or a setTimeout with a
small delay (less preferable).

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by PropGit** [comment] 2017-08-11 16:52
> @paragitadmin, do you have any recollection of how this feature came to be in the first place?

This is an interesting conversation.  Perhaps you meant to ask me?

The shared link feature was devised to quickly allow a user (like a Parallaxian, for example) to get a link to any project they created for including in a Learn Tutorial, email, etc.  The point was for the link to be persistent as long as the project existed, and to warn a user when deleting the project if there was a shared link to that project out in the wild.  This adds some safety in project maintenance... if a project is simply "shared" (public), it's easy for a user (Parallaxian or other) to delete a project without knowing it'd break published direction to view that project.

As it is, it's not perfect.  Without it, I'm not convinced we're better off.

**Comment by MatzElectronics** [comment] 2017-08-14 05:39
Seems to be working now that I applied fixes related to #1103.  Can anyone else please verify?

**Comment by MatzElectronics** [comment] 2018-05-31 06:19
Working, closing

**Closed by MatzElectronics** 2018-05-31 06:19 UTC
Labels: In Demo, Requires Verification, bug
