### ISSUE TITLE
Poor line following using sensor block.

### ISSUE THREAD

**Issue by mrodriguez-parallax** [parallaxinc/BlocklyProp#969] opened 2017-03-27 17:56 UTC
The line following is now  poor for this line following block.
![image](https://cloud.githubusercontent.com/assets/20686764/24369328/7ed24a86-12d8-11e7-8d23-c7ffd841d4f3.png)

I am working out of the line following tutorial on this link.
http://learn.parallax.com/tutorials/robot/scribbler-robot/navigating-sensors/simple-line-following

Up until recently the code for this tutorial performed relatively well. Now it doesn't matter if I use the printed tracks or electrical tape the S3 will not follow either type of line for more than a few seconds.

**Comment by kgracey** [comment] 2017-03-27 17:59
Miguel, this likely relates to the line sensor threshold values used in the
block (it assumes some values, like greater than 40). It would be helpful
to know what the analog values are from the "advanced S3 blocks". Could you
put the S3 over a line and program a system with those blocks to see what
numbers are coming out?

**Comment by kgracey** [comment] 2017-03-27 18:00
Code like this, but in the Demo site of course and with Communicate blocks
so you can see what's going on.
http://blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=1184

**Comment by dcarrier-parallax** [comment] 2017-04-06 03:05
Part of the problem is an issue in the block wrapper that is preventing the S3 robot from differentiating the center of a line from the absence of a line.  After this pull request is completed: https://github.com/parallaxinc/Scribbler-3_Library/pull/7, it will be easier to write example code that works well.

When the pull request is completed, I will verify that it has the intended effect on the block, but we will still need to create example line following code that more closely matches the examples given for the Scribbler 2 GUI.

**Comment by wstodghill** [comment] 2017-04-06 03:24
@dcarrier-parallax and @kgracey,

I agree with all this discussion. This problem has been difficult and giving me problems for some time. Code that I originally wrote and tested, just doesn't work anymore. I have yet to get any results close to the ones in the demo code written by Ben.

**Comment by MatzElectronics** [comment] 2017-04-30 10:19
A line sensor calibration block has been added to S3 C in Demo.  Please test by putting it at the beginning of a line following program.

**Comment by wstodghill** [comment] 2017-05-21 11:23
@MatzElectronics - been testing this and meeting with mixed results. When I look at the C for the routine, It appears to me that there might be an error (not sure though).

Here is a screen capture of the part in question...

![linesen](https://cloud.githubusercontent.com/assets/8891440/26283350/7ec5fe5e-3dec-11e7-902c-b3554f869e4f.JPG)

along with this that sets the variables...

![linsenvar](https://cloud.githubusercontent.com/assets/8891440/26283401/66c84ca2-3ded-11e7-808c-08b6da7ef016.JPG)

I believe that the Left variable numbers are 0 and 2, and the Right variable numbers are 1 and 3. They are mixed in the first Screen Capture routine above. (or am I wrong?).

**Comment by MatzElectronics** [comment] 2017-05-21 16:30
I think you're on to something....
Do you have simpleIDE?  Could you try fixing it there (make 0 and 1 left
and 2 and 3 right in the beginning when they are initially set) and see if
that makes anything better?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by wstodghill** [comment] 2017-05-22 14:09
I will try to version of this is BlocklProp today or tomorrow. I have an idea about something new to try.

**Comment by wstodghill** [comment] 2017-05-22 21:36
@MatzElectronics - This is written for the Left Line Sensor only - It calibrates the sensor by sensing the highest white and lowest black, then finds the average between the two. and tests the solution be letting you move the S3 around over the black line or the white surface. Similar, but I was thinking of setting separate values for the Left and Right Sensors. Might be good to average between the lowest white reading the highest black - will try that now as ver 2.0

http://demo.blockly.parallax.com/blockly/my/projects.jsp#915

**Comment by MatzElectronics** [comment] 2017-07-16 08:48
I think this is now as good as it's going to get...closing.

**Closed by MatzElectronics** 2017-07-16 08:48 UTC
Labels: bug, Requires Verification, Scribbler 3, Spin
