### ISSUE TITLE
Slim down number of blocks & categories presented for Hackable Electronic Badge projects

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#200] opened 2016-05-18 19:33 UTC
The Hackable Electronic Badge doesn't work with many of the blocks that are in other categories.  It would be very important (at least eventually) to get rid of these categories for HEB Projects.

Even though users CAN hack the hardware, they won't be able to use the "out of the box" connections to sensors, and they also won't be able to use any of the pin numbers in other blocks.

BlocklyProp is hugely important for HEB users, but as soon as they start HACKING, we expect they will move to the SimpleIDE [assuming propeller c is their language]

**Comment by DarkmatterVale** [comment] 2016-05-18 21:42
@michel-cf Is the support for custom-selecting blocks something you are planning on working on in the near future? Is it something that I should look at?

**Comment by michel-cf** [comment] 2016-06-12 10:44
Filtering blocks based on the board is now possible.
If you don't want a given category for "heb" add: `exlude="heb"`
If you want a given category only for "heb" add: `include="heb"` (This already has been done on the HEB category)

**Comment by michel-cf** [comment] 2016-06-12 11:16
Duplicate of #142

**Closed** 2016-06-12 11:43 UTC
