### ISSUE TITLE
S3 block: infrared (or LEDs) not producing functional code

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#365] opened 2016-07-13 21:33 UTC
@dcarrier-parallax please try this code:
![screen shot 2016-07-13 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/9534148/16820577/b522cd78-4906-11e6-8f28-f6584f98806a.png)
```
CON
  _clkmode = xtal1 + pll16x
  _xinfreq = 5_000_000

VAR

OBJ
  scribbler    : "Block_Wrapper"

PUB Setup
  Start


PUB Start

  repeat
    if Scribbler.ReadObstacle(Scribbler#LEFT)
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#RED)
      waitcnt(clkfreq / 1000 * 100 + cnt)

    else
      Scribbler.SetLED(Scribbler#LEFT, Scribbler#OFF)
      waitcnt(clkfreq / 1000 * 100 + cnt)
```
Because we don't have a Spin block for Print I am trying other ways to test the sensors using LEDs as feedback. So, I really don't know if the issue likes with your wrapper code around the LED control or the infrared sensors.

**Comment by dcarrier-parallax** [comment] 2016-07-14 21:17
Duplicate of: https://github.com/parallaxinc/BlocklyProp/issues/374, caused by crash of Block_Wrapper.spin

**Closed by dcarrier-parallax** 2016-07-14 21:18 UTC
