### ISSUE TITLE
BUG - Restore S3 Demo - works on Demo BlocklyProp Beta, but not on Live BlocklyProp Beta

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1057] opened 2017-06-22 19:33 UTC
Testing today shows that the restore S3 demo block does not work on the Live BlocklyProp Beta.

**Comment by wstodghill** [comment] 2017-06-23 06:25
@kgracey, @MatzElectronics, @zfi, - please take a look.

**Comment by wstodghill** [comment] 2017-06-24 00:45
Demo BlocklyProp Beta yields this "C" code screen...
![demo c restore](https://user-images.githubusercontent.com/8891440/27504268-339837ec-584c-11e7-9b5c-6cadad017220.JPG)

and the EEPROM Load Screen...
![demo load screen](https://user-images.githubusercontent.com/8891440/27504270-43b094b2-584c-11e7-8d7c-9fe48997daf6.JPG)

Live BlocklyProp Beta yields this "C" code screen...
![live c](https://user-images.githubusercontent.com/8891440/27504279-5c4f335c-584c-11e7-8b94-b72ea8ef6acb.JPG)

and this EEPROM Load Screen...
![live load screen](https://user-images.githubusercontent.com/8891440/27504283-70f70456-584c-11e7-9577-54f34564e69b.JPG)

**Comment by MatzElectronics** [comment] 2017-06-24 00:50
Jim is probably the only person who can fix this.  Basically that "pragma"
line is supposed to tell the server to ignore all of the C stuff and go
find the default S3 EEPROM image and load that instead.  Because it is all
handles on the server, and because the live server is not the same as the
demo server, that instruction will need to be added to the live site.

**Comment by wstodghill** [comment] 2017-06-24 03:40
@MatzElectronics - Thanks!

**Comment by zfi** [comment] 2017-06-25 07:11
The issue is that the Cloud Compiler service in the production system was not updated at the time the BlocklyProp service in the production system was upgraded. An update to the Cloud Compiler service should be ready to go Monday morning.

**Comment by PropGit** [comment] 2017-06-25 16:12
Thanks @wstodghill!

Thanks for following up on this, @MatzElectronics and @zfi!

**Comment by wstodghill** [comment] 2017-06-26 15:12
@PropGit - Glad to help! I love BlocklyProp and want it to be the best we can make it!

**Comment by zfi** [comment] 2017-06-26 18:16
The production Cloud Compiler servers were updated this morning. 

@wstodghill Can you take another spin on this issue and try to load the default library on the production site (blockly.parallax.com)?

**Comment by wstodghill** [comment] 2017-06-26 18:49
@zfi - Y'all got it! Brilliant - This one can be closed - unless you all want some further testing.

**Comment by zfi** [comment] 2017-06-26 19:17
Closing the issue.

**Closed by zfi** 2017-06-26 19:17 UTC
