### ISSUE TITLE
My Projects page sometimes shows "no results"

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#148] opened 2016-03-09 23:00 UTC
To reproduce.  
Have an account with several projects
Go to the My Projects page. 
Refresh until you see "no matching records found" (see screenshot)
Refresh again until you see the expected projects list

It is as though the server sometimes takes too long to respond with the list of projects, and the page treats the timeout as an empty list.  
<img width="1010" alt="screen shot 2016-03-09 at 4 56 48 pm" src="https://cloud.githubusercontent.com/assets/769072/13653614/6bceedc4-e618-11e5-8704-1f9e2b4b80f6.png">

**Comment by PropGit** [comment] 2016-03-10 01:43
Verified (kind of)... Clicking My Projects showed what I expected, and a refresh of the web page cleared it (as shown in the above post), but further refreshes or clicking on My Projects never showed the list again (always empty).  Tried more than 10 times.

**Comment by michel-cf** [comment] 2016-03-10 04:02
How do you check this? The list is loaded asynchronously, so to verify where the problem is you need to open your browser console and look at the requests being made.

**Comment by DarkmatterVale** [comment] 2016-05-04 20:38
Verified this is still an issue. I'm not sure why it is happening, because one second the project list is correct, then it cannot find any projects. The only way to fix the problem (once it occurs), is to restart the browser.

Another weird aspect of this issue...the problem appears to happen randomly. Sometimes I can reproduce the error, other times I cannot.

**Comment by PropGit** [comment] 2016-07-12 22:37
This appears to have been fixed by the simplified authentication enhancement which led up to PR #296.

**Closed by PropGit** 2016-07-12 22:37 UTC
Labels: bug, Priority 1, Retest with simplified authentication
