### ISSUE TITLE
S3 rotate the Scribbler robot block: ERROR

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#547] opened 2016-08-17 05:27 UTC
@kgracey and @dcarrier-parallax,

If I understand how this block should work - we have an error - regardless of setting of the around a radius in "value" - my S3 spins in place at the top speed (both wheels) for the degrees set. 

The rotational degree setting seems to have a slight error too - but this could be a calibration issue - will we have a user calibration block (per the Scribbler Spin Object?

![rotate_the_scribbler_robot_block](https://cloud.githubusercontent.com/assets/8891440/17725403/b71984da-6410-11e6-8c7e-5bd8e46cafe7.JPG)

**Comment by wstodghill** [comment] 2016-08-24 07:21
Anybody else tested this? As of yesterday, I still could not get it to work other that rotating in place.

**Comment by kgracey** [comment] 2016-08-24 17:13
@dcarrier-parallax is looking at this today. It might be best that if he can't readily figure out the issue that we simply remove the second line "around a radius". We will either modify the block or make it work as intended today.

**Comment by dcarrier-parallax** [comment] 2016-09-01 17:38
This was addressed by PR #670. Please Verify.

**Comment by kgracey** [comment] 2016-09-01 21:05
Tested and verified!

**Closed by kgracey** 2016-09-01 21:05 UTC
Labels: bug, In Demo, Priority 1, Requires Verification, Scribbler 3

**Comment by wstodghill** [comment] 2016-09-02 01:33
Verified here too! Works great!

**Comment by wstodghill** [comment] 2016-10-03 06:40
I do not believe this works properly in the current version (at least not on the live version of BlocklyProp.
