### ISSUE TITLE
Save As after block placement mangles project

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1123] opened 2017-08-03 17:46 UTC
In the Demo system this morning, the Save As feature seems to have mangled my project.

__I've tried this three times... same results each time _unless_ I tried adding a different block than the three shown in the description below.__

My original project looked like this:

![image](https://user-images.githubusercontent.com/1266318/28935146-661e5b7c-7838-11e7-9db5-eddb80b278f1.png)

I just modified it to add these blocks near the bottom:

![image](https://user-images.githubusercontent.com/1266318/28935567-d1b9f458-7839-11e7-8444-57b86b63150e.png)

and did a Save As on my project... then it prompted me (very briefly) that it had saved the project and then the overlay disappeared (faded away) quickly on it's own and left my screen looking like this:

![image](https://user-images.githubusercontent.com/1266318/28935183-87ca9b14-7838-11e7-86f1-2b18e50a4b70.png)

The project (except for the strangely-printed "forever") is invisible.  If I refresh the page, it tells me my project is not saved and I have to click the "Leave" button to continue with the refresh, but the project still looks the same afterwards. 

If I click the Save button and then refresh the browser, it appeared like this:

![image](https://user-images.githubusercontent.com/1266318/28935212-a1869e9a-7838-11e7-8993-b40b6c412bdb.png)

Every block is sitting (disconnected) on piled up on top of each other.  The project is broken and unusable without reconstructing all the block connections.

![image](https://user-images.githubusercontent.com/1266318/28935216-aaf98384-7838-11e7-9831-62bd35176202.png)

**Comment by PropGit** [comment] 2017-08-03 18:04
I updated the first post as it seem that it has something to do with the three blocks I added + clicking Save As.

If I simply add a comment block instead of the three blocks noted above, then it did Save As properly.

**Comment by MatzElectronics** [comment] 2017-08-03 18:06
Which 3 blocks did you add?

**Comment by PropGit** [comment] 2017-08-03 18:09
These three:

![image](https://user-images.githubusercontent.com/1266318/28935567-d1b9f458-7839-11e7-8444-57b86b63150e.png)

I just tried again... starting with the original, then doing a Save Project As, then adding the three blocks (above) and then clicking Save.  The result is that the editor _looks_ fine, but if you go back to "My Projects" and select this new Saved As project, it still appears as invisible except for the mangled "forever" text... exactly like after the Save Project As action that I originally reported.  

Ugh... can't get anywhere.  I'm wondering if some of the new functionality just introduced is causing this.

**Comment by MatzElectronics** [comment] 2017-08-03 18:10
Try a force refresh.  Your browser may be choking on cached code.

**Comment by PropGit** [comment] 2017-08-03 18:11
I have, multiple times - I documented that in the first post. ;-)

**Comment by MatzElectronics** [comment] 2017-08-03 18:11
Sorry - scrambling to figure it out...

**Comment by MatzElectronics** [comment] 2017-08-03 18:17
Found it.  Now to fix it...

**Comment by PropGit** [comment] 2017-08-03 18:18
Is it from code added for the Auto Save Project As feature?

**Comment by MatzElectronics** [comment] 2017-08-03 18:20
No, it's from some block type checking designed to prevent users from attaching ints to string inputs and vice-versa.  The glitch is being caused by a race condition where the type isn't being set properly before it's checked.

**Comment by PropGit** [comment] 2017-08-03 19:11
Retested after PR #1124 and that prevented the project mangling that I experienced.

**Comment by MatzElectronics** [comment] 2017-08-03 19:53
Okay, thanks!  Closing.

**Closed by MatzElectronics** 2017-08-03 19:53 UTC
Labels: bug, Priority 1
